import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Hero from '@/components/Hero'
import HeroSmall from '@/components/HeroSmall'
import Services from '@/components/Services'
import Testimonios from '@/components/Testimonios'
import Doctora from '@/components/Doctora'
import Clinica from '@/components/Clinica'
import Preguntas from '@/components/Preguntas'
import Contacto from '@/components/Contacto'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   

      <body id='body' className={inter.className}>
        <nav className=' w-full shadow-md'>
          <NavBar />
        </nav>
        <main className='w-[90%] mx-auto '>
          <Hero />
        </main>
        <HeroSmall />
        <Services />
        <Testimonios />
        <Doctora />
        <Preguntas />
        <Contacto />
        {children}
      </body>
    </html>
  )
}
